# style.py

# --- DESIGN TOKENS (AZOTA STYLE GUIDE) ---
COLOR_PRIMARY = "#2361AE"   
COLOR_SECONDARY = "#111827"  
COLOR_ERROR = "#FDBC35"     
COLOR_SUCCESS = "#209C53"   
COLOR_FAIL = "#E74C3C"       

COLOR_BG_LIGHT = "#F4F6F9"  
COLOR_CARD_WHITE = "#FFFFFF" 
COLOR_BORDER = "#E2E8F0"     
COLOR_GRAY_TEXT = "#6B7280"

FONT_FAMILY = "SF Pro Display"